# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janitriapp', '0002_newswebsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newswebsite',
            name='news_website',
        ),
        migrations.AddField(
            model_name='newswebsite',
            name='interest',
            field=models.IntegerField(choices=[(1, 'Entertainment'), (2, 'Sports'), (3, 'Travel')], default=1),
        ),
    ]
